### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by btc721** [chad-m-carlson/arrow-tech#27]
I did another made up batch,  number 48.  Duplicate serial numbers were able to be inputted and showed up on the calibration certificate.

**Comment by chad-m-carlson** [comment]
This should be fixed. Only unique dosimeters can be entered into the same batch. 

There will also be a quick blue message every time a dosimeter is created in the system. Which will be every time there is a calibration entered for the first bit. I can remove it if you want but it was helping me make sure everything was working correctly instead of reading through tons of lines on the server.

Please run another quick test batch through and verify everything is working correctly with this, and that it didn't break anything else.

**Comment by btc721** [comment]
It seems to work now.
