### ISSUE TITLE
Hermetic seal

### ISSUE THREAD

**Issue by btc721** [chad-m-carlson/arrow-tech#31]
Can we get an option for "none" in hermetic seal?

**Comment by chad-m-carlson** [comment]
Would that be for the whole batch? Or just different models of dosimeters?

**Comment by btc721** [comment]
Yes, it would be for the whole batch.

**Comment by chad-m-carlson** [comment]
I think I got it working. 

- In the calibration entry form, if you don't want the hermetic seal un-check the `VAC Required?` box and it will default the VAC Pass box to passing.

- I set it up assuming that the hermetic seal would coincide with the model, so in the CoC if that model doesn't require a hermetic seal check, that column won't even show up in the table.

- In the failure report, since all models are listed there, if the hermetic seal check is not required, that column will be populated with "N/A"

Check it out and see how it works.

**Comment by btc721** [comment]
No matter what I do no I can not click the "submit dosimeter calibration" button in the calibration form.

**Comment by chad-m-carlson** [comment]
There's a server error happening in the deployed version. I'll take a look

**Comment by chad-m-carlson** [comment]
It's fixed, just had to restart the server

**Comment by btc721** [comment]
That seems to work okay.  If I go back in to edit a dosimeter, the "vac required?' box is checked again.  This doesn't seem to affect the reports.

**Comment by chad-m-carlson** [comment]
This should be fixed now

**Comment by btc721** [comment]
I agree. This is fixed.
